name: Build Only

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: actions/checkout@v2

      - name: Install Deps
        run: pip3.9 install lambda-setuptools twine

      - name: Build
        run: |
          python3.9 setup.py sdist ldist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
